{ pkgs, ... }:

let
  candidateText = builtins.concatStringsSep "\n" [
    "# Generated by OpenClaw declarative evolution candidate v0."
    "# Review and stage explicitly; OpenClaw does not write or activate this file."
    "{ lib, ... }:"
    "{"
    "  services.openclaw.components = lib.mkAfter ["
    "    \"observerUi\""
    "  ];"
    "}"
    ""
  ];
  candidateHash = "aed7e917ee5074b9fc063a953c3bd49d49f5a952bebe6b962d7fb4d5d33b3206";
  candidateModule = builtins.toFile "openclaw-managed.nix" candidateText;
  candidateFixture = {
    fileSystems."/" = {
      device = "none";
      fsType = "tmpfs";
    };
    boot.loader.grub.devices = pkgs.lib.mkForce [ "nodev" ];
  };
  prebuiltCandidateToplevel = assert builtins.hashString "sha256" candidateText == candidateHash;
    (import (pkgs.path + "/nixos/lib/eval-config.nix") {
    system = pkgs.stdenv.hostPlatform.system;
    modules = [
      ./openclaw-declarative-evolution-activation-base.nix
      candidateModule
      candidateFixture
    ];
  }).config.system.build.toplevel;
  prebuiltCandidateDerivation =
    builtins.unsafeDiscardStringContext prebuiltCandidateToplevel.drvPath;
  candidateStoreName = builtins.baseNameOf (toString prebuiltCandidateToplevel);
  candidateStoreHash = builtins.substring 0 32 candidateStoreName;
  candidateDerivationName = builtins.baseNameOf prebuiltCandidateDerivation;
  candidateBinaryCache = pkgs.runCommand "openclaw-activation-candidate-binary-cache" {
    __structuredAttrs = true;
    exportReferencesGraph.candidate = [ prebuiltCandidateToplevel ];
    nativeBuildInputs = [ pkgs.jq pkgs.nix pkgs.zstd ];
  } ''
    mkdir -p "$out/nar" "$out/realisations" "$out/debuginfo" "$out/log"
    record="$(${pkgs.jq}/bin/jq -c --arg path '${prebuiltCandidateToplevel}' \
      '.candidate[] | select(.path == $path)' "$NIX_ATTRS_JSON_FILE")"
    test -n "$record"

    nar_path="$out/nar/${candidateStoreHash}.nar.zst"
    ${pkgs.nix}/bin/nix-store --dump '${prebuiltCandidateToplevel}' \
      | ${pkgs.zstd}/bin/zstd --quiet > "$nar_path"
    file_hash="$(${pkgs.nix}/bin/nix-hash --base32 --type sha256 --flat "$nar_path")"
    file_size="$(${pkgs.coreutils}/bin/stat -c %s "$nar_path")"
    nar_hash="$(${pkgs.jq}/bin/jq -r '.narHash' <<<"$record")"
    nar_size="$(${pkgs.jq}/bin/jq -r '.narSize' <<<"$record")"
    references="$(${pkgs.jq}/bin/jq -r \
      '.references | map(split("/")[-1]) | join(" ")' <<<"$record")"

    printf '%s\n' \
      'StorePath: ${prebuiltCandidateToplevel}' \
      'URL: nar/${candidateStoreHash}.nar.zst' \
      'Compression: zstd' \
      "FileHash: sha256:$file_hash" \
      "FileSize: $file_size" \
      "NarHash: $nar_hash" \
      "NarSize: $nar_size" \
      "References: $references" \
      'Deriver: ${candidateDerivationName}' \
      > "$out/${candidateStoreHash}.narinfo"
    printf '%s\n' 'StoreDir: /nix/store' > "$out/nix-cache-info"
  '';
  candidateCacheArchive = pkgs.runCommand "openclaw-activation-candidate-cache.tar.gz" {
    allowedReferences = [ ];
    nativeBuildInputs = [ pkgs.gnutar pkgs.gzip ];
  } ''
    tar --create --gzip --file "$out" --directory '${candidateBinaryCache}' .
  '';
in
{
  name = "openclaw-declarative-evolution-activation";

  nodes.machine = { ... }: {
    imports = [ ./openclaw-declarative-evolution-activation-base.nix ];

    virtualisation = {
      cores = 2;
      memorySize = 4096;
      diskSize = 8192;
      additionalPaths = [ prebuiltCandidateToplevel ];
    };
  };

  testScript = ''
    import json
    import shlex

    auth_config = "/run/openclaw-activation-vm-curl.conf"
    core_url = "http://127.0.0.1:4100"
    event_hub_url = "http://127.0.0.1:4101"
    prebuilt_candidate_toplevel = "${prebuiltCandidateToplevel}"
    candidate_cache_archive = "${candidateCacheArchive}"

    def command_output(command):
        return machine.succeed(command).strip()

    def request_json(base_url, path, method="GET", payload=None, authenticated=False):
        args = [
            "curl",
            "--silent",
            "--show-error",
            "--fail-with-body",
            "--request",
            method,
        ]
        if authenticated:
            args.extend(["--config", auth_config])
        if payload is not None:
            args.extend([
                "--header",
                "content-type: application/json",
                "--data",
                json.dumps(payload, separators=(",", ":")),
            ])
        args.append(f"{base_url}{path}")
        return json.loads(command_output(shlex.join(args)))

    def core_json(path, method="GET", payload=None):
        return request_json(core_url, path, method, payload, authenticated=True)

    def approve(approval_id, reason):
        result = core_json(
            f"/approvals/{approval_id}/approve",
            "POST",
            {"approvedBy": "nixos-vm-release-gate", "reason": reason},
        )
        assert result["ok"] is True, result
        assert result["approval"]["status"] == "approved", result
        return result

    def execute_current_task():
        result = core_json("/operator/step", "POST", {})
        assert result["ok"] is True, result
        assert result["ran"] is True, result
        assert result["blocked"] is False, result
        return result

    def service_pid(unit):
        return int(command_output(
            f"systemctl show {shlex.quote(unit)} --property=MainPID --value"
        ))

    def prepare_candidate_cache():
        machine.succeed("mkdir -p /run/openclaw-candidate-cache")
        machine.succeed(
            f"tar --extract --gzip --file {shlex.quote(candidate_cache_archive)} "
            "--directory /run/openclaw-candidate-cache"
        )
        machine.succeed("test -f /run/openclaw-candidate-cache/nix-cache-info")
        machine.succeed(f"nix-store --delete {shlex.quote(prebuilt_candidate_toplevel)}")
        machine.fail(f"test -e {shlex.quote(prebuilt_candidate_toplevel)}")

    start_all()
    baseline_units = [
        "openclaw-event-hub.service",
        "openclaw-core.service",
        "openclaw-session-manager.service",
        "openclaw-browser-runtime.service",
        "openclaw-screen-sense.service",
        "openclaw-screen-act.service",
        "openclaw-system-sense.service",
        "openclaw-system-heal.service",
        "openclaw-hostd.service",
        "polkit.service",
        "backdoor.service",
    ]
    for unit in baseline_units:
        machine.wait_for_unit(unit)

    for port in range(4100, 4108):
        machine.wait_until_succeeds(
            f"curl --silent --fail http://127.0.0.1:{port}/health"
        )
    assert command_output("systemd-detect-virt --vm") in ["kvm", "qemu"]

    machine.succeed(f"""
      umask 077
      {{
        printf 'header = "Authorization: Bearer '
        tr -d '\\n' < /var/lib/openclaw/operator-token
        printf '"\\n'
      }} > {auth_config}
    """)

    generation_before = command_output("readlink -f /run/current-system")
    profile_before = command_output("readlink -f /nix/var/nix/profiles/system")
    core_pid_before = service_pid("openclaw-core.service")
    hostd_pid_before = service_pid("openclaw-hostd.service")
    assert core_pid_before > 0
    assert hostd_pid_before > 0
    machine.fail("test -e /etc/nixos/openclaw-managed.nix")
    machine.fail("systemctl is-active --quiet observer-ui.service")
    prepare_candidate_cache()

    hostd_environment = command_output(
        "systemctl show openclaw-hostd.service --property=Environment --value"
    )
    assert "OPENCLAW_HOSTD_ACTIVATION_ENABLED=true" in hostd_environment
    assert "OPENCLAW_HOSTD_ACTIVATION_HELPER=/nix/store/" in hostd_environment
    assert "OPENCLAW_HOSTD_ACTIVATION_SUDO=/run/wrappers/bin/sudo" in hostd_environment
    assert "OPENCLAW_HOSTD_ROLLBACK_HELPER=/nix/store/" in hostd_environment
    assert "OPENCLAW_HOSTD_ROLLBACK_SUDO=/run/wrappers/bin/sudo" in hostd_environment
    assert "OPENCLAW_NIXOS_FLAKE=" not in hostd_environment
    assert "OPENCLAW_NIXOS_FLAKE_ATTRIBUTE=" not in hostd_environment
    assert command_output(
        "systemctl show openclaw-hostd.service --property=NoNewPrivileges --value"
    ) == "no"
    assert command_output(
        "systemctl show openclaw-hostd.service --property=ProtectSystem --value"
    ) == "yes"

    health_before = core_json(
        "/plugins/native-adapter/declarative-evolution/activation-decision"
    )
    assert health_before["ok"] is False, health_before
    assert health_before["blocked"] is True, health_before
    assert health_before["reason"] == "staging_task_id_required", health_before

    with subtest("staging resolves one real prebuilt candidate closure without host mutation"):
        staging = core_json(
            "/plugins/native-adapter/declarative-evolution/staging-tasks",
            "POST",
            {
                "changes": [{"operation": "enable_component", "component": "observerUi"}],
                "confirm": True,
            },
        )
        assert staging["ok"] is True, staging
        assert staging["task"]["type"] == "native_declarative_evolution_staging", staging
        assert staging["task"]["status"] == "queued", staging
        assert staging["approval"]["status"] == "pending", staging
        staging_task_id = staging["task"]["id"]
        staging_approval_id = staging["approval"]["id"]
        candidate_hash = staging["candidate"]["candidateHash"]

        approve(
            staging_approval_id,
            "Approve one hash-bound candidate build inside the disposable VM.",
        )
        staging_step = execute_current_task()
        staging_task = staging_step["task"]
        staging_execution = staging_task["nativeDeclarativeEvolution"]["execution"]
        assert staging_task["status"] == "completed", staging_step
        assert staging_execution["status"] == "passed", staging_execution
        assert staging_execution["candidateHash"] == candidate_hash, staging_execution
        assert staging_execution["validation"]["status"] == "passed", staging_execution
        assert staging_execution["evaluation"]["status"] == "passed", staging_execution
        assert staging_execution["build"]["status"] == "passed", staging_execution
        evaluated_closure = staging_execution["build"]["outputPath"]
        assert evaluated_closure == staging_execution["evaluation"]["toplevelPath"]
        assert evaluated_closure == prebuilt_candidate_toplevel
        assert evaluated_closure.startswith("/nix/store/")
        assert evaluated_closure != generation_before
        assert command_output(
            f"stat -c '%U:%G:%a' {shlex.quote(staging_execution['staging']['directory'])}"
        ) == "openclaw-service:openclaw:750"
        assert command_output(
            f"stat -c '%U:%G:%a' {shlex.quote(staging_execution['staging']['path'])}"
        ) == "openclaw-service:openclaw:640"
        assert command_output("readlink -f /run/current-system") == generation_before
        assert command_output("readlink -f /nix/var/nix/profiles/system") == profile_before
        machine.fail("test -e /etc/nixos/openclaw-managed.nix")

    with subtest("approved activation decision remains non-mutating"):
        health_gate = core_json(
            f"/plugins/native-adapter/declarative-evolution/health-gate?taskId={staging_task_id}"
        )
        assert health_gate["ok"] is True, health_gate
        assert health_gate["assessment"]["status"] == "eligible_for_activation_review", health_gate
        assert health_gate["evaluatedClosure"]["path"] == evaluated_closure, health_gate
        assert health_gate["closureIntegrity"]["status"] == "verified", health_gate

        decision = core_json(
            "/plugins/native-adapter/declarative-evolution/activation-decisions",
            "POST",
            {
                "taskId": staging_task_id,
                "decision": "approve_activation_review",
                "confirm": True,
            },
        )
        assert decision["ok"] is True, decision
        assert decision["review"]["hostHealth"]["status"] == "healthy", decision
        decision_task_id = decision["task"]["id"]
        approve(
            decision["approval"]["id"],
            "Approve the exact host-health-bound activation decision inside the disposable VM.",
        )
        decision_step = execute_current_task()
        decision_task = decision_step["task"]
        decision_execution = decision_task["nativeDeclarativeEvolution"]["execution"]
        assert decision_task["status"] == "completed", decision_step
        assert decision_execution["activation"] == "approved_for_future_activation", decision_execution
        assert decision_execution["governance"]["executesActivation"] is False, decision_execution
        assert command_output("readlink -f /run/current-system") == generation_before
        machine.fail("test -e /etc/nixos/openclaw-managed.nix")

    with subtest("fixed root helper rejects an unbound closure before mutation"):
        helper_path = command_output(
            "systemctl show openclaw-hostd.service --property=Environment --value "
            "| tr ' ' '\\n' | sed -n 's/^OPENCLAW_HOSTD_ACTIVATION_HELPER=//p'"
        )
        status, _ = machine.execute(
            "runuser -u openclaw-hostd -- /run/wrappers/bin/sudo --non-interactive "
            f"{shlex.quote(helper_path)} {candidate_hash} /etc/passwd rejected-request"
        )
        assert status != 0
        assert command_output("readlink -f /run/current-system") == generation_before
        machine.fail("test -e /etc/nixos/openclaw-managed.nix")

    with subtest("explicit activation switches one bound generation and passes independent health"):
        activation = core_json(
            "/plugins/native-adapter/declarative-evolution/activation-tasks",
            "POST",
            {"activationDecisionTaskId": decision_task_id, "confirm": True},
        )
        assert activation["ok"] is True, activation
        assert activation["task"]["type"] == "native_declarative_evolution_activation", activation
        assert activation["task"]["status"] == "queued", activation
        assert activation["approval"]["status"] == "pending", activation
        activation_task_id = activation["task"]["id"]
        activation_approval_id = activation["approval"]["id"]

        approve(
            activation_approval_id,
            "Approve one fixed managed-config generation switch inside the disposable VM.",
        )
        activation_step = execute_current_task()
        activation_task = activation_step["task"]
        execution = activation_task["nativeDeclarativeEvolution"]["execution"]
        receipt = execution["executionReceipt"]
        helper = receipt["helperEvidence"]

        assert activation_task["id"] == activation_task_id
        assert activation_task["status"] == "completed", activation_step
        assert execution["status"] == "passed", execution
        assert execution["activationExecuted"] is True, execution
        assert execution["generationSwitched"] is True, execution
        assert execution["postActivationHealth"]["status"] == "healthy", execution
        assert execution["rollbackEvidence"] is None, execution
        assert execution["governance"]["executesRollback"] is False, execution
        assert execution["governance"]["automaticRollback"] is False, execution
        assert receipt["status"] == "passed", receipt
        assert receipt["candidateHash"] == candidate_hash, receipt
        assert receipt["evaluatedClosurePath"] == evaluated_closure, receipt
        assert receipt["previousGenerationPath"] == generation_before, receipt
        assert receipt["activatedGenerationPath"] == evaluated_closure, receipt
        assert receipt["activatedProfilePath"] == evaluated_closure, receipt
        assert receipt["rollbackSnapshotId"] == receipt["requestId"], receipt
        assert receipt["previousTargetPresent"] is False, receipt
        assert receipt["rollbackExecuted"] is False, receipt
        assert helper["registry"] == "nixsoma-managed-config-activation-helper-v0", helper
        assert helper["generationBefore"] == generation_before, helper
        assert helper["rollbackSnapshotId"] == receipt["rollbackSnapshotId"], helper
        assert helper["previousTargetPresent"] is False, helper
        assert helper["generationAfter"] == evaluated_closure, helper
        assert helper["profileAfter"] == evaluated_closure, helper
        assert helper["targetHashAfter"] == candidate_hash, helper
        assert helper["targetInstalled"] is True, helper

        assert command_output("readlink -f /run/current-system") == evaluated_closure
        assert command_output("readlink -f /nix/var/nix/profiles/system") == evaluated_closure
        assert command_output(
            "sha256sum /etc/nixos/openclaw-managed.nix | cut -d' ' -f1"
        ) == candidate_hash
        machine.wait_for_unit("observer-ui.service")
        machine.wait_until_succeeds("curl --silent --fail http://127.0.0.1:4170/health")
        assert service_pid("openclaw-core.service") == core_pid_before
        assert service_pid("openclaw-hostd.service") == hostd_pid_before
        rollback_snapshot_id = receipt["rollbackSnapshotId"]
        rollback_snapshot_path = f"/var/lib/nixsoma-managed-config-rollbacks/{rollback_snapshot_id}"
        assert command_output(
            f"stat -c '%U:%G:%a' {shlex.quote(rollback_snapshot_path)}"
        ) == "root:root:700"
        machine.succeed(f"test -f {shlex.quote(rollback_snapshot_path + '/candidate-hash')}")

    with subtest("terminal approval cannot replay activation"):
        generation_after = command_output("readlink -f /run/current-system")
        status_args = [
            "curl",
            "--silent",
            "--output",
            "/tmp/reapprove-activation.json",
            "--write-out",
            "%{http_code}",
            "--request",
            "POST",
            "--config",
            auth_config,
            "--header",
            "content-type: application/json",
            "--data",
            json.dumps({"reason": "Attempt forbidden activation replay."}),
            f"{core_url}/approvals/{activation_approval_id}/approve",
        ]
        assert command_output(shlex.join(status_args)) == "409"
        assert command_output("readlink -f /run/current-system") == generation_after
        assert service_pid("openclaw-core.service") == core_pid_before
        assert service_pid("openclaw-hostd.service") == hostd_pid_before

    with subtest("explicit rollback restores the exact previous generation and consumes its snapshot"):
        rollback = core_json(
            "/plugins/native-adapter/declarative-evolution/rollback-tasks",
            "POST",
            {"activationTaskId": activation_task_id, "confirm": True},
        )
        assert rollback["ok"] is True, rollback
        assert rollback["task"]["type"] == "native_declarative_evolution_rollback", rollback
        assert rollback["task"]["status"] == "queued", rollback
        assert rollback["approval"]["status"] == "pending", rollback
        rollback_task_id = rollback["task"]["id"]
        rollback_approval_id = rollback["approval"]["id"]
        assert rollback["approvalBinding"]["activationTaskId"] == activation_task_id, rollback
        assert rollback["approvalBinding"]["activationReceiptHash"] == receipt["receiptHash"], rollback
        assert rollback["approvalBinding"]["rollbackSnapshotId"] == rollback_snapshot_id, rollback
        assert rollback["approvalBinding"]["previousGenerationPath"] == generation_before, rollback

        approve(
            rollback_approval_id,
            "Approve one exact previous-generation rollback inside the disposable VM.",
        )
        rollback_step = execute_current_task()
        rollback_task = rollback_step["task"]
        rollback_execution = rollback_task["nativeDeclarativeEvolution"]["execution"]
        rollback_receipt = rollback_execution["rollbackReceipt"]
        rollback_helper = rollback_receipt["helperEvidence"]

        assert rollback_task["id"] == rollback_task_id
        assert rollback_task["status"] == "completed", rollback_step
        assert rollback_execution["status"] == "passed", rollback_execution
        assert rollback_execution["postRollbackHealth"]["status"] == "healthy", rollback_execution
        assert rollback_execution["governance"]["executesRollback"] is True, rollback_execution
        assert rollback_execution["governance"]["automaticRollback"] is False, rollback_execution
        assert rollback_receipt["status"] == "passed", rollback_receipt
        assert rollback_receipt["activationReceiptHash"] == receipt["receiptHash"], rollback_receipt
        assert rollback_receipt["rollbackSnapshotId"] == rollback_snapshot_id, rollback_receipt
        assert rollback_receipt["previousGenerationPath"] == generation_before, rollback_receipt
        assert rollback_receipt["activatedGenerationPath"] == evaluated_closure, rollback_receipt
        assert rollback_receipt["rollbackExecuted"] is True, rollback_receipt
        assert rollback_receipt["generationRestored"] is True, rollback_receipt
        assert rollback_receipt["snapshotConsumed"] is True, rollback_receipt
        assert rollback_helper["registry"] == "nixsoma-managed-config-rollback-helper-v0", rollback_helper
        assert rollback_helper["generationBefore"] == evaluated_closure, rollback_helper
        assert rollback_helper["generationAfter"] == generation_before, rollback_helper
        assert rollback_helper["profileAfter"] == generation_before, rollback_helper
        assert rollback_helper["targetPresentAfter"] is False, rollback_helper
        assert rollback_helper["snapshotConsumed"] is True, rollback_helper

        assert command_output("readlink -f /run/current-system") == generation_before
        assert command_output("readlink -f /nix/var/nix/profiles/system") == generation_before
        machine.fail("test -e /etc/nixos/openclaw-managed.nix")
        machine.fail(f"test -e {shlex.quote(rollback_snapshot_path)}")
        machine.wait_until_succeeds("! systemctl is-active --quiet observer-ui.service")
        assert service_pid("openclaw-core.service") == core_pid_before
        assert service_pid("openclaw-hostd.service") == hostd_pid_before

    with subtest("terminal approval and consumed root snapshot reject rollback replay"):
        status_args = [
            "curl",
            "--silent",
            "--output",
            "/tmp/reapprove-rollback.json",
            "--write-out",
            "%{http_code}",
            "--request",
            "POST",
            "--config",
            auth_config,
            "--header",
            "content-type: application/json",
            "--data",
            json.dumps({"reason": "Attempt forbidden rollback replay."}),
            f"{core_url}/approvals/{rollback_approval_id}/approve",
        ]
        assert command_output(shlex.join(status_args)) == "409"
        rollback_helper_path = command_output(
            "systemctl show openclaw-hostd.service --property=Environment --value "
            "| tr ' ' '\\n' | sed -n 's/^OPENCLAW_HOSTD_ROLLBACK_HELPER=//p'"
        )
        status, _ = machine.execute(
            "runuser -u openclaw-hostd -- /run/wrappers/bin/sudo --non-interactive "
            f"{shlex.quote(rollback_helper_path)} {shlex.quote(rollback_snapshot_id)}"
        )
        assert status != 0
        assert command_output("readlink -f /run/current-system") == generation_before
        machine.fail("test -e /etc/nixos/openclaw-managed.nix")
        assert service_pid("openclaw-core.service") == core_pid_before
        assert service_pid("openclaw-hostd.service") == hostd_pid_before

    audit = request_json(event_hub_url, "/events/audit?limit=1000")
    assert not any(
        item["type"].startswith("cloud_provider.")
        for item in audit["items"]
    ), audit
    machine.succeed(
        "systemctl is-active --quiet "
        "openclaw-event-hub.service openclaw-core.service "
        "openclaw-session-manager.service openclaw-browser-runtime.service "
        "openclaw-screen-sense.service openclaw-screen-act.service "
        "openclaw-system-sense.service openclaw-system-heal.service "
        "openclaw-hostd.service backdoor.service"
    )
    assert command_output("systemctl --failed --no-legend --plain") == ""

    print(json.dumps({
        "registry": "nixsoma-declarative-evolution-activation-rollback-vm-v0",
        "stagingTaskId": staging_task_id,
        "activationDecisionTaskId": decision_task_id,
        "activationTaskId": activation_task_id,
        "candidateHash": candidate_hash,
        "generationBefore": generation_before,
        "generationAfter": evaluated_closure,
        "activationReceiptHash": receipt["receiptHash"],
        "rollbackTaskId": rollback_task_id,
        "rollbackReceiptHash": rollback_receipt["receiptHash"],
        "helperRegistry": helper["registry"],
        "postActivationHealth": execution["postActivationHealth"]["status"],
        "observerActivatedBeforeRollback": True,
        "observerInactiveAfterRollback": True,
        "corePidPreserved": service_pid("openclaw-core.service") == core_pid_before,
        "hostdPidPreserved": service_pid("openclaw-hostd.service") == hostd_pid_before,
        "approvalReplayBlocked": True,
        "rollbackApprovalReplayBlocked": True,
        "rootSnapshotReplayBlocked": True,
        "providerEgress": False,
        "browserAction": False,
        "rollbackExecuted": True,
        "automaticRollback": False,
        "failedUnits": 0,
    }, indent=2))
  '';
}
